### ISSUE TITLE
neuroglancer-position-widget-input doesn't allow user input

### ISSUE THREAD

**Issue by nkemnitz** [seung-lab/ng-extend#16]
The text input field `.neuroglancer-position-widget-input` doesn't allow text selection or input, preventing users from jumping to a specific position in the dataset.
Windows 10 + Chrome  81.0.4044.122

**Comment by kaikue** [comment]
This was fixed by https://github.com/seung-lab/ng-extend/commit/6b13bb0938b7b4c58f86af367c9bf42d3030579f I believe
